"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContext } from "@/context/AuthContext";
import { useContext } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { currentUser } = useContext(AuthContext);

  // const RequireAuth = ({ children }: any) => {
  //   const router = useRouter();

  //   if (!currentUser) {
  //     router.push("/login");
  //     return null;
  //   }

  //   return children;
  // };

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <RequireAuth></RequireAuth> */}
        {children}
      </body>
    </html>
  );
}
