"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContext } from "@/context/AuthContext";
import { useContext } from "react";
import { useRouter } from "next/router";
import { AuthProvider } from "@/auth";
import CheckAuth from "@/checkAuth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <RequireAuth></RequireAuth> */}
        <CheckAuth>
          <AuthProvider>{children}</AuthProvider>
        </CheckAuth>
      </body>
    </html>
  );
}
